use Mix.Config

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# NomadWeb.Endpoint.init/2 when load_from_system_env is
# true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task
# which you typically run after static files are built.
config :nomad, NomadWeb.Endpoint,
  load_from_system_env: true,
  url: [host: (System.get_env("HOST") || "95.213.195.185"), port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

config :nomad, NomadWeb.Endpoint,
  secret_key_base: System.get_env("SECRET_KEY_BASE")

# Configure your database
config :nomad, Nomad.Repo,
  adapter: Ecto.Adapters.Postgres,
  url: System.get_env("DATABASE_URL"),
  pool_size: String.to_integer(System.get_env("POOL_SIZE") || "20")

config :nomad,
  aws_bucket: System.get_env("S3_BUCKET"),
  aws_host: System.get_env("S3_HOST")

config :ex_aws,
  access_key_id: [System.get_env("S3_ACCESS_KEY_ID") || "", :instance_role],
  secret_access_key: [System.get_env("S3_ACCESS_KEY") || "", :instance_role],
  region: System.get_env("S3_REGION") || "",
  s3: [
    scheme: "http://",
    host: System.get_env("S3_HOST"),
    region: System.get_env("S3_REGION") || "",
    port: 80
  ]
